### ISSUE TITLE
Download plugin from a GitHub repository

### ISSUE THREAD

**Issue by Trollwut** [keeweb/keeweb-plugins#1]
Hi folks!

I wanted to start creating a KeeWeb theme. I signed the plugin as mentioned in the plugin creation wiki page, but now I'm lost.

What do I have to do so that I can import the theme/plugin in KeeWeb? If I simply enter the GitHub repo or the release file, I get a simple `Error loading plugin manifest`

This would be the little repo so far: https://github.com/Trollwut/keeweb-theme-trollwut-pink-dark

**Comment by antelle** [comment]
Hi! You should host it somewhere, e.g. on github pages. Something like this:
https://plugins.keeweb.info/plugins/keewebhttp/manifest.json

**Comment by antelle** [comment]
If you're testing locally, you can set up an http server and load the plugin from it.

**Comment by Trollwut** [comment]
Mh, doesn't work for me. Did the steps of the wiki page and servers says it's up with SSL at port 8081. But importing the plugin via KeeWeb still gives me the error.

Browser also says it's no safe connection.

**Comment by antelle** [comment]
Maybe if you load the plugin in chrome and click Proceed, it will work? Not sure.

**Comment by Trollwut** [comment]
What exactly do you mean by loading which page and proceed?

If you mean the security alert that it's not safe then yes, I can ignore this message and see the contents of `./`, which is my plugin directory

But KeePass won't get the manifest.json :C

**Comment by antelle** [comment]
Yes, I meant that alert. So, it didn't help 😢 
Well, you can actually host keeweb on your server together with the plugin and then it will work. 
Added an issue to improve plugin hosting docs / tools: https://github.com/keeweb/keeweb/issues/721

**Comment by Trollwut** [comment]
Yes, a "beginner's doc" would be pretty cool. Just so that someone doesn't have to be a pro in every part of the software and can concentrate on developing a plugin :)

Will try other ways these days, tomorrow it's getting late. Thanks mate!
