### ISSUE TITLE
Open KeeWeb for unlocking when KeeWebHttp asks for a password

### ISSUE THREAD

**Issue by Akeboshiwind** [keeweb/keeweb-plugins#2]
Hi, I'm not sure if this would be better here or on the main repo.
If this is the wrong place, I'll move it over to the main repo.

I usually keep KeeWeb locked at most points, so it would be useful if KeePass was opened in the foreground when my browser plugin asks KeePassHttp for a password.

**Comment by antelle** [comment]
The problem is, it's asking for a password every single time you open a website. Do you want keeweb to prompt you? Then we can create a psetting for it.
This is a wrong repo, but it's fine to keep this issue here, I'll disable issues here today.

**Comment by Akeboshiwind** [comment]
Hmm, you're right.
I think this is a case where I need to choose between convenience and security.

Thanks for your help :)

**Comment by Akeboshiwind** [comment]
Where would a good place be to submit issues for KeeWebHttp btw?

**Comment by antelle** [comment]
Actually keepasshttp could ask for a password only when you're explicitly asking for it, e.g. when you click a lock button or other interaction. But they ask to unlock the app just on website load, unfortunately.

**Comment by antelle** [comment]
A right place is keeweb project, just as any other issues :)
